# Aprovechamiento en la computación para la enseñanza del álgebra lineal.

## Matrices 

Cómo ingresar matrices:
Recordemos que las matrices son listas de listas (un (0,2)-tensor). La idea es programar de manera manual (en bruto) para después utilizar las paqueterías y/o librerías que nos permitan simplificar el código. En este caso, estamos utilizando VSCode + Jupyter + Python en el contexto de enseñar álgebra lineal a través de la computación. Este entorno incluye muchas herramientas útiles, como el formato de texto, LaTeX, entre otras.

$$
A = \begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9 
\end{bmatrix}.
$$


In [18]:
A=[[1,2,3],[4,5,6],[7,8,9]] #Matriz de 3x3. Nótese que se escribe por renglones. El símbolo "=" se traduce como "definimos tal cosa". 
print(A)

def print_matrix(matrix): #Uso del ingles para implementar código. 
    for renglon in matrix: #Para cada renglon de mi matriz imprime en renglon. 
        print(renglon)

print_matrix(A) #Nótese que los sálidas al imprimir la matriz tienen distintas sintaxis. 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


# Operaciones básicas de matrices. 
## Suma de matrices. 
Recordando que solo se pueden sumar matrices del mismo tamaño, definimos la suma entrada a entrada. 
$$A\oplus B=(a_{ij})\oplus (b_{ij})=(a_{ij}+b_{ij}).$$
En esta parate se trabaja el como ingresar a un elemento específico de una matriz tomando en cuenta que Python (y otros lenguajes de programación) empiezan a contar desde "0". La longitud de una lista (cuantos elementos contiene) y el rango de un número. Además de crear la matriz cero, que nos ayudará a sustituir en ella cada suma que realicemos de manera ordenada. 

In [19]:
print(A[1][2]) #A[renglon][columna]=A[i][j]=a_{ij}.
B=[[9,8,7],[6,5,4],[3,2,1]]
# C=[[A[i][j]+B[i][j]]] rellenar la matriz resultante de sumar. 
# Vamos a crear una matriz de puros ceros. 
rows= len(A) #longitud de A como listas de listas (cuantas sublistas tiene A).
cols=len(A[0])
C=[[0 for j in range(cols)]for i in range(rows)]
print(C)

def sum_matrix(matrix_1,matrix_2):
    result=[[0 for j in range(cols)]for i in range(rows)]
    for i in range(rows): #range(3)->[0,1,2] i va a tomar los valores 0,1 y 2. 
        for j in range(cols):
            result[i][j]=matrix_1[i][j]+matrix_2[i][j] #Una sustitución de valores. 
    return result
print_matrix(sum_matrix(A,B))

6
[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


## El producto por un escalar. 
Recordemos que de una matriz por un escalar se define entrada a entrada. 
$$c\odot A =c\odot (a_{ij})=(c\cdot a_{ij}).$$

In [20]:
def product_scalar(matrix,c):
    return [[matrix[i][j]*c for j in range(len(matrix[0]))] for i in range(len(matrix))]
print_matrix(product_scalar(A,5))

[5, 10, 15]
[20, 25, 30]
[35, 40, 45]


**Transponer matrices**, que es en sí misma una transformación lineal en el espacio de matrices, cuya definición es cambiar renglones por columnas (en orden) o vice versa. 
$$A^t=(a_{ij})^t:=(a_{ji}).$$

In [21]:
def transpose(matrix):
    return [[A[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
print_matrix(transpose(A))

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


**La matriz identidad**, es una matriz cuadrada de $n\times n$, con 1's en la diagonal, en el idioma de los índices quiere decir que $i=j$ (diagonal) y ceros sí $i\neq j$ (fuera de la diagonal).  

In [22]:
def indentity_n(n):
    I=[[0]*n for i in range(n)] 
    for i in range(n): #range(n)=[0,1,2,...,n-1] i toma los valores 0,1,2,..., n-1
        I[i][i]=1
    return I
print_matrix(indentity_n(3))

[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


## Multiplicación de matrices. 
$$
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
\cdot
\begin{bmatrix}
b_{11} & b_{12} & \cdots & b_{1l} \\
b_{21} & b_{22} & \cdots & b_{2l} \\
\vdots & \vdots & \ddots & \vdots \\
b_{n1} & b_{n2} & \cdots & b_{nl}
\end{bmatrix}
=
\begin{bmatrix}
c_{11} & c_{12} & \cdots & c_{1l} \\
c_{21} & c_{22} & \cdots & c_{2l} \\
\vdots & \vdots & \ddots & \vdots \\
c_{m1} & c_{m2} & \cdots & c_{ml}
\end{bmatrix},
$$

$$
c_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj}=a_{i1}b_{1j}+a_{i2}b_{2j}+\cdots+a_{in}b_{nj}.
$$

La multiplicación de matrices depende del número de renglones y columnas de la siguiente manera:
$$A_{m\times n}B_{n\times l}=C_{m\times l}.$$
Nótese que esta definición hace que el producto de matrices no sea conmutativo, también obtenemos un tercer subíndice con cual tratar. Además, la matriz cero que construimos no es igual a la matriz cero que se usa en la suma. 

In [23]:
def mult_matrix(A,B):
    rows_A=len(A)
    cols_A=len(A[0])
    cols_B=len(B[0])
    C=[[0]*cols_B for i in range(rows_A)] #Matriz cero para el producto. 

    for i in range(rows_A): #range(rows_A)=[0,1,2,...,m-1].
        for j in range(cols_B): #range(cols_B)=[0,1,2,...,l-1].
            for k in range(cols_A): #range(cols_A)=[0,1,2,...,n-1].
                C[i][j]+=A[i][k]*B[k][j]
    return C
print_matrix(mult_matrix(A,B))

[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


## Matriz asociada a una transformación lineal. 
Recordemos que la matriz asociada a una transformación lineal depende de la base que tomemos para generar la matriz, es decir, si tenemos $T:\mathbb{R}^n \rightarrow \mathbb{R}^m$ y $\beta=\{e_1,...,e_n\}$ una base, la matriz asociada a la transformación en la base $\beta$ es $[T]_\beta=[T(e_1)\;\; T(e_2)\;\;\cdots \;\; T(e_n)]$ donde $T(e_i)$ son vectores columna. 

Por ejemplo $T:\mathbb{R}^2\rightarrow \mathbb{R}^2$, dada por $T(x,y)=(2x+y,x-y)$ en la base canónica $\beta=\{(1,0),(0,1)\}$ obtenemos la matriz asociada  
$$ [T]_\beta=[T(1,0)\;\; T(0,1)]= \begin{bmatrix} 2 & 1 \\ 1 & -1\end{bmatrix}. $$

In [24]:
def matrix_aso(map,base):
    return[[map(v)[i] for v in base] for i in range(len(base))]
#Ingresemos una transformación lineal y una base específicas para hacer trabajar al código. 
def T(v): #Definimos nuestra transformación lineal como función.
    x,y=v
    return (2*x+y,x-y)
base=[(1,0),(0,1)] #Ingresamos la base (puede ser una base distinta).
print_matrix(matrix_aso(T,base)) 


[2, 1]
[1, -1]


## Numpy para las operaciones con matrices. 
Después de programar por uno mismo las operaciones básicas de matrices utilizaremos la libreria **numpy**, la cual incluye el concepto de "array", que maneja una sintaxis distinta tanto en el código como en la salida al imprimir una matriz. 

In [25]:
import numpy as np

# Definición de las matrices
A_np = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_np = np.array(B)  # Asegúrate de que 'B' esté definido previamente

# Imprimir matrices y resultados en un solo print
print(f"\n{B_np}\n")

# Suma de matrices
C_np = A_np + B_np
print(f"{C_np}\n")

# Producto de matrices
D_np = np.dot(A_np, B_np)
print(f"{D_np}\n")

# Transpuesta de A_np
T_np = A_np.T
print(f"{T_np}\n")

# Matriz de ceros (4x3)
zeros_matrix = np.zeros((4, 3))
print(f"{zeros_matrix}\n")

# Matriz identidad 5x5
identity_matrix = np.eye(5)
print(f"{identity_matrix}")


[[9 8 7]
 [6 5 4]
 [3 2 1]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Finalmente, en numpy existe muchos *submódulos*, como *np.linalg*, que nos ayudan tanto en la parte teórica como el rango de una matriz y la parte practica como el determinante o la inversa de una matriz. 

In [26]:
#Que mas puede hacer numpy 
rango=np.linalg.matrix_rank(A)
print(rango)
det=np.linalg.det(A)
print(det)


2
0.0


## Extra (Tensores, matrices y tensorflow).
Los tensores son funciones $T:V^*\times \cdots \times V^* \times V\times \cdots \times V\rightarrow \mathbb{K}$, multilineales, es decir, $$T(v_1,\dots ,\lambda v_i+w,\dots, v_{r+s})=\lambda T(v_1,\cdots,v_i,\cdots,v_{r+s})+T(v_1,\cdots,w,\cdots,v_{r+s}),$$
donde $V^*\times \cdots \times V^*=(V^*)^r$, $V\times \cdots \times V=V^s$ y $\lambda$ un escalar en el campo $\mathbb{K}$.

Cuando decirmos que una matriz es un $(0,2)$-tensor se tiene que precisar a que nos referimos y remarcar las diferencias entre definiciones. Para fijar ideas tomemos $V=\mathbb{R}^2$, las matrices son transformaciones lineales $A:\mathbb{R}^2\rightarrow \mathbb{R}^2$, que estrictamente no es un tensor, pues el contradominio no es el campo $\mathbb{R}$. Para "ajustarlo" a la definición de tensor debemos definir una transformación auxiliar, $T_A:\mathbb{R}^2\times \mathbb{R}^2\rightarrow \mathbb{R}$, dada por $T_A(v,w)=v^tAw$. Nótese que $T_A$ ya es un $(0,2)$-tensor,es decir, una transformación multilineal; el $0$ se refiere a que no aparece el espacio dual $(\mathbb{R}^2)^*$ y el $2$ son las dos copias de $\mathbb{R}^2$ en el dominio de $T_A$.

Veamos como ingresar "matrices" en el la librería de tensorflow. 

In [27]:
import tensorflow as tf
# Definimos dos matrices ((0,2)-tensores).
A = tf.constant([[1, 2], [3, 4]])  # Matriz 2x2.
B = tf.constant([[0, 5], [6, 7]])  # Matriz 2x2.
print(A) # Muestra la matriz directamente en la consola con la sintaxis de tensorflow.
print(B.numpy())  # Convierte el tensor a una matriz NumPy antes de imprimir.

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[0 5]
 [6 7]]


## Otros tipos de tensores.

Tomemos un $(0,3)$-tensor, $ T:(\mathbb{R}^2)^3\rightarrow \mathbb{R}$. Este tensor también tiene una "matriz" asociada, donde las entradas de la matriz vienen dadas por los coeficientes 
$ T_{ijk}=T(e_i,e_j,e_k),$ con $\beta = \{e_1,e_2\}$ base de $\mathbb{R}^2$ y los índices $i,\, j,\, k$ tomando los valores $1,2$ y. Esto no es una matriz, sino un arreglo cúbico donde la cara de enfrente y la de atras tienes los arreglos 
$$
\begin{bmatrix} T_{111} & T_{112}  \\  T_{121} & T_{122}  \\  \end{bmatrix}, \quad \begin{bmatrix} T_{211} & T_{212}  \\  T_{221} & T_{222}  \\  \end{bmatrix}.
$$

La "matriz asociada" de un $(0,4)$-tensor ya no tiene un arreglo visual que lo represente, pero sí tiene un arreglo en la sintaxis de tensorflow. 

¿Qué sucede con los tensores del tipo $(r,s)$ con $r\neq 0$? Por ejemplo un $(1,2)$-tensor tiene como coeficientes $T^i_{jk}$ donde el supraíndice $i$ representa los elementos de la base en el espacio dual $V^*$, pero gracias al álgebra lineal, se puede *bajar* el índice para transformarlo en un $(0,3)$-tensor usando la matriz asociada al producto interno $g_{il}$ de la siguiente manera: 
$$ T_{ijk}=g_{il}T^l_{jk}.$$ 
Veamos el código.




In [28]:
T_03 = tf.constant([[[1, 2], [3, 4]],[[5, 6], [7, 8]]]) #Un (0,3)-tensor en un espacio de dimensión 2.
T_04 = tf.constant([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],[[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]) #Un (0,4)-tensor. 
T_12 = tf.constant([
    [[1, 2], [3, 4]],  # Primer vector resultante
    [[5, 6], [7, 8]]   # Segundo vector resultante
])

g = tf.constant([
    [1, 0], 
    [0, 1]
])

# Realizamos la contracción usando tensordot para bajar el índice
T_03_lowered = tf.tensordot(g, T_12, axes=1)  # Contracción del primer índice

tf.print(T_03)
tf.print(T_04)
tf.print(T_12) 
tf.print("Tensor (0,3) después de bajar un índice:", T_03_lowered)
#Notese que no hay diferencias entre las sintaxis de T_03, T_12 y T_03_lowered, las diferencias son puramente matemáticas.  

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Tensor (0,3) después de bajar un índice: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# El producto tensorial. 

Sea $T_1$ un tensor de tipo $(r_1, s_1)$ y $T_2$ un tensor de tipo $(r_2, s_2)$.  
El producto tensorial de $T_1$ y $T_2$ es un nuevo tensor de tipo $(r_1 + r_2, s_1 + s_2)$, definido por:

\begin{align*}
(T_1 \otimes T_2) & (\theta^1, \dots, \theta^{r_1 + r_2}, v_1, \dots, v_{s_1 + s_2}) =  \\
& T_1 (\theta^1, \dots, \theta^{r_1}, v_1, \dots, v_{s_1}) \cdot T_2 (\theta^{r_1+1}, \dots, \theta^{r_1 + r_2}, v_{s_1+1}, \dots, v_{s_1+s_2})
\end{align*}

donde $\theta^i$ son vectores duales y $v_j$ son vectores.

Si queremos hacer el producto tensorial de dos matrices $A$ y $B$, nos tenemos que apoyar en $T_A$ y $T_B$, más aun, si queremos lo coeficientes de este nuevo tensor tenemos que hacer los siguiente calculos:
$$ (A\otimes B)_{ijkl}=(T_A \otimes T_B)_{ijkl}=T_A\otimes T_B(e_i,e_j,e_k,e_l)=T_A(e_i,e_j)T_B(e_k,e_l). $$

Aquí las susticiones son bastante mas numerosas, pero la libreria tensorflow tiene el submódulo *tf.tensordot* (que ya usamos anteriormente) que nos ayuda a minimizar el trabajo manual.
Curiosamente, el producto tensorial sí nos permite "multiplicar" matrices de distintos tamaños sin restricción.  

In [29]:
A = tf.constant([[1, 2], [3, 4]])  # Matriz 2x2
B = tf.constant([[5, 6], [7, 8]])  # Matriz 2x2

tensor_product = tf.tensordot(A, B, axes=0) #axes 
print(tensor_product)

tf.Tensor(
[[[[ 5  6]
   [ 7  8]]

  [[10 12]
   [14 16]]]


 [[[15 18]
   [21 24]]

  [[20 24]
   [28 32]]]], shape=(2, 2, 2, 2), dtype=int32)


Cuando axes=0, no hay contracción de índices, lo que significa que cada elemento de A se "multiplica" con cada elemento de B, generando un tensor de orden superior; axes=1 es el producto matricial (similar a $AB$ si las dimensiones lo permiten); axes=2 es la contracción sobre dos dimensiones, similar al producto interno en tensores de orden mayor.